import { Category, Supplier, Product } from './types';

export const SEED_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Cloud Computing', description: 'Enterprise cloud hosting, compute, and server solutions.' },
  { id: 'cat-2', name: 'Cybersecurity', description: 'Advanced firewall, endpoint protection, and penetration testing.' },
  { id: 'cat-3', name: 'AI & Data Analytics', description: 'Machine learning modules, pipeline integration, and smart insights.' },
  { id: 'cat-4', name: 'Hardware & Devices', description: 'Premium workstations, enterprise servers, and networking hubs.' },
  { id: 'cat-5', name: 'Servers & Systems', description: 'Rack servers, custom system builds, and enterprise compute nodes.' },
  { id: 'cat-6', name: 'Enterprise Drives (SSD/HDD)', description: 'High-end SSD/HDD storage media for enterprise workloads.' },
  { id: 'cat-7', name: 'Switches & Routers', description: 'Core, edge, and data-center network switching and routing hardware.' },
  { id: 'cat-8', name: 'RAID & Expansion Cards', description: 'RAID controllers and expansion cards for enterprise servers.' },
  { id: 'cat-9', name: 'Network Adapters (NICs)', description: 'High-throughput Ethernet and fiber network interface cards.' },
  { id: 'cat-10', name: 'Transceivers & Cabling', description: 'SFP/QSFP modules and enterprise networking cabling components.' }
];

export const SEED_SUPPLIERS: Supplier[] = [
  { id: 'sup-1', name: 'Apex Semiconductors', contactName: 'Helen Carter', email: 'helen@apex-semi.com', phone: '+1 (555) 234-5678', address: '101 Silicon Way, San Jose, CA' },
  { id: 'sup-2', name: 'Vertex Systems Group', contactName: 'Marcus Aurel', email: 'procurement@vertex-sys.com', phone: '+1 (555) 876-5432', address: '404 Network Ave, Austin, TX' },
  { id: 'sup-3', name: 'Aether Cloud Distributors', contactName: 'Sarah Jenkins', email: 'accounts@aether-dist.com', phone: '+44 20 7946 0192', address: '88 London Bridge Rd, London, UK' },
  { id: 'sup-4', name: 'NetAxis Distribution Co.', contactName: 'Rashid Karim', email: 'sales@netaxis.example', phone: '+880 2-41022027', address: 'Banani DOHS, Dhaka, Bangladesh' }
];

export const SEED_PRODUCTS: Omit<Product, 'createdAt'>[] = [
  { id: 'prod-1', sku: 'INV-CLD-ENT', name: 'Enterprise Cloud Suite Pro', category: 'Cloud Computing', supplierId: 'sup-3', supplierName: 'Aether Cloud Distributors', description: 'Hybrid cloud framework with integrated backup, 99.99% uptime SLA.', price: 1200, cost: 450, stock: 45, minStock: 10, unit: 'license/mo' },
  { id: 'prod-2', sku: 'INV-CYB-FW', name: 'Sentinel Firewall Gateway X1', category: 'Cybersecurity', supplierId: 'sup-2', supplierName: 'Vertex Systems Group', description: 'Enterprise stateful firewall with real-time threat intelligence and SSL decrypt.', price: 2450, cost: 1100, stock: 8, minStock: 5, unit: 'unit' },
  { id: 'prod-3', sku: 'INV-AI-ANL', name: 'Predictive Insights Engine', category: 'AI & Data Analytics', supplierId: 'sup-1', supplierName: 'Apex Semiconductors', description: 'AI module that integrates with local databases to compile predictive sales dashboards.', price: 3200, cost: 1500, stock: 3, minStock: 5, unit: 'license' },
  { id: 'prod-4', sku: 'INV-HW-NODE', name: 'Inovexa Compute Node C4', category: 'Hardware & Devices', supplierId: 'sup-1', supplierName: 'Apex Semiconductors', description: '2U Rackmount Server, Dual Intel Xeon, 128GB RAM, 2TB SSD.', price: 4100, cost: 2300, stock: 12, minStock: 4, unit: 'unit' },
  { id: 'prod-5', sku: 'INV-CYB-EP', name: 'Endpoint Protection Agent', category: 'Cybersecurity', supplierId: 'sup-2', supplierName: 'Vertex Systems Group', description: 'Device-level antivirus with automated patch remediation and zero-day defense.', price: 45, cost: 15, stock: 120, minStock: 20, unit: 'user/yr' },
  { id: 'prod-6', sku: 'INV-CLD-DB', name: 'Managed Database Cluster', category: 'Cloud Computing', supplierId: 'sup-3', supplierName: 'Aether Cloud Distributors', description: 'Highly scalable database cluster with automated replication and daily backups.', price: 650, cost: 220, stock: 2, minStock: 5, unit: 'instance/mo' },
  { id: 'prod-pc-mikrotik-huananzhi-x99', sku: 'INV-PC-MIKROTIK-HUANANZHI-X99', name: 'PC-Mikrotik-HUANANZHI X99 CD4 LGA 2011-3 XEON X99', category: 'Servers & Systems', supplierId: 'sup-1', supplierName: 'Apex Semiconductors', description: 'Custom MikroTik Router / Server Build', price: 34600, cost: 23528, stock: 8, minStock: 2, unit: 'unit' },
  { id: 'prod-dell-poweredge-r630', sku: 'INV-DELL-POWEREDGE-R630', name: 'Dell PowerEdge R630 Server', category: 'Servers & Systems', supplierId: 'sup-1', supplierName: 'Apex Semiconductors', description: 'Servers & Systems hardware component from the Inovexa enterprise catalog.', price: 185000, cost: 125800, stock: 8, minStock: 2, unit: 'unit' },
  { id: 'prod-hgst-12tb-10k-sas-hdd', sku: 'INV-HGST-12TB-10K-SAS-HDD', name: 'HGST Ultrastar C10K1800 1.2TB 10,000 RPM SAS 12Gb/s 2.5-inch Enterprise HDD', category: 'Enterprise Drives (SSD/HDD)', supplierId: 'sup-2', supplierName: 'Vertex Systems Group', description: 'Enterprise Drives (SSD/HDD) hardware component from the Inovexa enterprise catalog.', price: 16000, cost: 10880, stock: 48, minStock: 10, unit: 'unit' },
  { id: 'prod-hpe-7-68tb-nvme-ssd', sku: 'INV-HPE-7-68TB-NVME-SSD', name: 'HPE 7.68TB NVMe Gen4 High Read Intensive SFF BC Enterprise SSD', category: 'Enterprise Drives (SSD/HDD)', supplierId: 'sup-2', supplierName: 'Vertex Systems Group', description: 'Enterprise Drives (SSD/HDD) hardware component from the Inovexa enterprise catalog.', price: 16000, cost: 10880, stock: 48, minStock: 10, unit: 'unit' },
  { id: 'prod-cisco-nexus-93180yc-ex', sku: 'INV-CISCO-NEXUS-93180YC-EX', name: 'Cisco Nexus 9300 N9K-C93180YC-EX 48x 10/25GbE SFP28 + 6x 100GbE QSFP28 Network Switch', category: 'Switches & Routers', supplierId: 'sup-4', supplierName: 'NetAxis Distribution Co.', description: 'Switches & Routers hardware component from the Inovexa enterprise catalog.', price: 98000, cost: 66640, stock: 14, minStock: 4, unit: 'unit' },
  { id: 'prod-juniper-mx80', sku: 'INV-JUNIPER-MX80', name: 'Juniper Networks MX80 Universal Router', category: 'Switches & Routers', supplierId: 'sup-4', supplierName: 'NetAxis Distribution Co.', description: 'Switches & Routers hardware component from the Inovexa enterprise catalog.', price: 98000, cost: 66640, stock: 14, minStock: 4, unit: 'unit' },
  { id: 'prod-intel-d3-s4510-480gb', sku: 'INV-INTEL-D3-S4510-480GB', name: 'Intel SSD D3-S4510 Series 480GB 2.5-inch SATA III Enterprise SSD', category: 'Enterprise Drives (SSD/HDD)', supplierId: 'sup-2', supplierName: 'Vertex Systems Group', description: 'Enterprise Drives (SSD/HDD) hardware component from the Inovexa enterprise catalog.', price: 16000, cost: 10880, stock: 48, minStock: 10, unit: 'unit' },
  { id: 'prod-intel-dc-s3610-200gb', sku: 'INV-INTEL-DC-S3610-200GB', name: 'Intel SSD DC S3610 Series 200GB 2.5-inch SATA III Enterprise SSD', category: 'Enterprise Drives (SSD/HDD)', supplierId: 'sup-2', supplierName: 'Vertex Systems Group', description: 'Enterprise Drives (SSD/HDD) hardware component from the Inovexa enterprise catalog.', price: 16000, cost: 10880, stock: 48, minStock: 10, unit: 'unit' },
  { id: 'prod-intel-dc-s4500-240gb', sku: 'INV-INTEL-DC-S4500-240GB', name: 'Intel SSD DC S4500 Series 240GB 2.5-inch SATA III Enterprise SSD', category: 'Enterprise Drives (SSD/HDD)', supplierId: 'sup-2', supplierName: 'Vertex Systems Group', description: 'Enterprise Drives (SSD/HDD) hardware component from the Inovexa enterprise catalog.', price: 16000, cost: 10880, stock: 48, minStock: 10, unit: 'unit' },
  { id: 'prod-intel-d3-s4510-series-480gb', sku: 'INV-INTEL-D3-S4510-SERIES-480GB', name: 'Intel SSD D3-S4510 Series 480GB SATA Enterprise SSD (Alternative Carrier)', category: 'Enterprise Drives (SSD/HDD)', supplierId: 'sup-2', supplierName: 'Vertex Systems Group', description: 'Enterprise Drives (SSD/HDD) hardware component from the Inovexa enterprise catalog.', price: 16000, cost: 10880, stock: 48, minStock: 10, unit: 'unit' },
  { id: 'prod-mellanox-40g-dual-sfp', sku: 'INV-MELLANOX-40G-DUAL-SFP', name: 'Mellanox ConnectX-3 EN MCX312B-XCCT Dual-Port 10G/40G SFP+ Network Adapter', category: 'Network Adapters (NICs)', supplierId: 'sup-4', supplierName: 'NetAxis Distribution Co.', description: 'Network Adapters (NICs) hardware component from the Inovexa enterprise catalog.', price: 12000, cost: 8160, stock: 28, minStock: 8, unit: 'unit' },
  { id: 'prod-intel-x710-da2-10g', sku: 'INV-INTEL-X710-DA2-10G', name: 'Intel Ethernet Converged Network Adapter X710-DA2 Dual-Port SFP+ 10GbE', category: 'Network Adapters (NICs)', supplierId: 'sup-4', supplierName: 'NetAxis Distribution Co.', description: 'Network Adapters (NICs) hardware component from the Inovexa enterprise catalog.', price: 12000, cost: 8160, stock: 28, minStock: 8, unit: 'unit' },
  { id: 'prod-intel-x520-da2-10g', sku: 'INV-INTEL-X520-DA2-10G', name: 'Intel Ethernet Server Adapter X520-DA2 Dual-Port SFP+ 10GbE', category: 'Network Adapters (NICs)', supplierId: 'sup-4', supplierName: 'NetAxis Distribution Co.', description: 'Network Adapters (NICs) hardware component from the Inovexa enterprise catalog.', price: 12000, cost: 8160, stock: 28, minStock: 8, unit: 'unit' },
  { id: 'prod-dell-1-8tb-10k-sas-hdd', sku: 'INV-DELL-1-8TB-10K-SAS-HDD', name: 'Dell 1.8TB 10K RPM SAS 12Gbps 512e 2.5-inch SFF Enterprise Hot-Plug HDD', category: 'Enterprise Drives (SSD/HDD)', supplierId: 'sup-2', supplierName: 'Vertex Systems Group', description: 'Enterprise Drives (SSD/HDD) hardware component from the Inovexa enterprise catalog.', price: 16000, cost: 10880, stock: 48, minStock: 10, unit: 'unit' },
  { id: 'prod-supermicro-dual-sfp-v211', sku: 'INV-SUPERMICRO-DUAL-SFP-V211', name: 'Supermicro AOC-STGN-i2S Dual-Port 10GbE SFP+ PCI-e Controller Card (v2.11)', category: 'Network Adapters (NICs)', supplierId: 'sup-4', supplierName: 'NetAxis Distribution Co.', description: 'Network Adapters (NICs) hardware component from the Inovexa enterprise catalog.', price: 12000, cost: 8160, stock: 28, minStock: 8, unit: 'unit' },
  { id: 'prod-intel-d7-p5520-7-68tb', sku: 'INV-INTEL-D7-P5520-7-68TB', name: 'Solidigm D7-P5520 Series 7.68TB NVMe PCIe 4.0 x4 U.2 2.5-inch Enterprise SSD', category: 'Enterprise Drives (SSD/HDD)', supplierId: 'sup-2', supplierName: 'Vertex Systems Group', description: 'Enterprise Drives (SSD/HDD) hardware component from the Inovexa enterprise catalog.', price: 16000, cost: 10880, stock: 48, minStock: 10, unit: 'unit' },
  { id: 'prod-supermicro-10g-2port-v20', sku: 'INV-SUPERMICRO-10G-2PORT-V20', name: 'Supermicro AOC-STGN-i2S Dual-Port 10GbE SFP+ PCI-e Controller Card (v2.0)', category: 'Network Adapters (NICs)', supplierId: 'sup-4', supplierName: 'NetAxis Distribution Co.', description: 'Network Adapters (NICs) hardware component from the Inovexa enterprise catalog.', price: 12000, cost: 8160, stock: 28, minStock: 8, unit: 'unit' },
  { id: 'prod-supermicro-10g-2port-v20-pro', sku: 'INV-SUPERMICRO-10G-2PORT-V20-PRO', name: 'Supermicro AOC-STGN-i2S Dual-Port 10GbE SFP+ PCI-e Controller Card (Pro Carrier)', category: 'Network Adapters (NICs)', supplierId: 'sup-4', supplierName: 'NetAxis Distribution Co.', description: 'Network Adapters (NICs) hardware component from the Inovexa enterprise catalog.', price: 12000, cost: 8160, stock: 28, minStock: 8, unit: 'unit' },
  { id: 'prod-patch-cord-om4-100g', sku: 'INV-PATCH-CORD-OM4-100G', name: 'LC-LC OM4 Multimode Duplex 100G Fiber Patch Cord', category: 'Transceivers & Cabling', supplierId: 'sup-4', supplierName: 'NetAxis Distribution Co.', description: 'Transceivers & Cabling hardware component from the Inovexa enterprise catalog.', price: 6500, cost: 4420, stock: 64, minStock: 12, unit: 'pcs' },
  { id: 'prod-samsung-pm863a-1-92tb', sku: 'INV-SAMSUNG-PM863A-1-92TB', name: 'Samsung PM863a Series 1.92TB SATA III 2.5-inch Enterprise SSD', category: 'Enterprise Drives (SSD/HDD)', supplierId: 'sup-2', supplierName: 'Vertex Systems Group', description: 'Enterprise Drives (SSD/HDD) hardware component from the Inovexa enterprise catalog.', price: 16000, cost: 10880, stock: 48, minStock: 10, unit: 'unit' },
  { id: 'prod-dell-emc-intel-dc-p4510-1tb', sku: 'INV-DELL-EMC-INTEL-DC-P4510-1TB', name: 'Dell Intel SSD DC P4510 Series 1.0TB NVMe PCIe 3.1 x4 U.2 2.5-inch Enterprise SSD', category: 'Enterprise Drives (SSD/HDD)', supplierId: 'sup-2', supplierName: 'Vertex Systems Group', description: 'Enterprise Drives (SSD/HDD) hardware component from the Inovexa enterprise catalog.', price: 16000, cost: 10880, stock: 48, minStock: 10, unit: 'unit' },
  { id: 'prod-cisco-qsfp-40g-sr4', sku: 'INV-CISCO-QSFP-40G-SR4', name: 'Cisco QSFP-40G-SR4 40GBASE-SR4 QSFP+ Transceiver Module', category: 'Transceivers & Cabling', supplierId: 'sup-4', supplierName: 'NetAxis Distribution Co.', description: 'Transceivers & Cabling hardware component from the Inovexa enterprise catalog.', price: 6500, cost: 4420, stock: 64, minStock: 12, unit: 'pcs' },
  { id: 'prod-mellanox-linkx-qsfp28-100g', sku: 'INV-MELLANOX-LINKX-QSFP28-100G', name: 'Mellanox MMA1B00-C100D LinkX 100GBASE-SR4 QSFP28 Optical Transceiver', category: 'Transceivers & Cabling', supplierId: 'sup-4', supplierName: 'NetAxis Distribution Co.', description: 'Transceivers & Cabling hardware component from the Inovexa enterprise catalog.', price: 6500, cost: 4420, stock: 64, minStock: 12, unit: 'pcs' },
  { id: 'prod-mellanox-connectx5-25gbe-dual', sku: 'INV-MELLANOX-CONNECTX5-25GBE-DUA', name: 'Mellanox ConnectX-5 EN MCX512A-ADAT Dual-Port 25GbE SFP28 PCIe Network Adapter', category: 'Network Adapters (NICs)', supplierId: 'sup-4', supplierName: 'NetAxis Distribution Co.', description: 'Network Adapters (NICs) hardware component from the Inovexa enterprise catalog.', price: 12000, cost: 8160, stock: 28, minStock: 8, unit: 'unit' },
  { id: 'prod-intel-xxv710-da2-25g', sku: 'INV-INTEL-XXV710-DA2-25G', name: 'Intel Ethernet Network Adapter XXV710-DA2 Dual-Port SFP28 25GbE', category: 'Network Adapters (NICs)', supplierId: 'sup-4', supplierName: 'NetAxis Distribution Co.', description: 'Network Adapters (NICs) hardware component from the Inovexa enterprise catalog.', price: 12000, cost: 8160, stock: 28, minStock: 8, unit: 'unit' },
  { id: 'prod-dell-r640-poweredge', sku: 'INV-DELL-R640-POWEREDGE', name: 'Dell PowerEdge R640 Server', category: 'Servers & Systems', supplierId: 'sup-1', supplierName: 'Apex Semiconductors', description: 'Servers & Systems hardware component from the Inovexa enterprise catalog.', price: 185000, cost: 125800, stock: 8, minStock: 2, unit: 'unit' },
  { id: 'prod-fujitsu-1g-four-port-lan', sku: 'INV-FUJITSU-1G-FOUR-PORT-LAN', name: 'Fujitsu D3045-A11 Quad-Port 1GbE PCIe Ethernet Network Card', category: 'Network Adapters (NICs)', supplierId: 'sup-4', supplierName: 'NetAxis Distribution Co.', description: 'Network Adapters (NICs) hardware component from the Inovexa enterprise catalog.', price: 12000, cost: 8160, stock: 28, minStock: 8, unit: 'unit' },
  { id: 'prod-fujitsu-d3045-a11-quad-port', sku: 'INV-FUJITSU-D3045-A11-QUAD-PORT', name: 'Fujitsu D3045-A11 Quad-Port 1GbE PCIe Ethernet Network Card (Bulk Edition)', category: 'Network Adapters (NICs)', supplierId: 'sup-4', supplierName: 'NetAxis Distribution Co.', description: 'Network Adapters (NICs) hardware component from the Inovexa enterprise catalog.', price: 12000, cost: 8160, stock: 28, minStock: 8, unit: 'unit' },
  { id: 'prod-dell-broadcom-57412-10gbe', sku: 'INV-DELL-BROADCOM-57412-10GBE', name: 'Dell Broadcom 57412 Dual-Port 10GbE SFP+ PCIe Network Adapter', category: 'Network Adapters (NICs)', supplierId: 'sup-4', supplierName: 'NetAxis Distribution Co.', description: 'Network Adapters (NICs) hardware component from the Inovexa enterprise catalog.', price: 12000, cost: 8160, stock: 28, minStock: 8, unit: 'unit' },
  { id: 'prod-dell-poweredge-nvme-pcie-extender', sku: 'INV-DELL-POWEREDGE-NVME-PCIE-EXT', name: 'Dell PowerEdge NVMe PCIe Extender Expansion Card', category: 'RAID & Expansion Cards', supplierId: 'sup-1', supplierName: 'Apex Semiconductors', description: 'RAID & Expansion Cards hardware component from the Inovexa enterprise catalog.', price: 22000, cost: 14960, stock: 22, minStock: 6, unit: 'unit' },
  { id: 'prod-mikrotik-routeros-x86-level6-ssd', sku: 'INV-MIKROTIK-ROUTEROS-X86-LEVEL6', name: 'MikroTik RouterOS x86 Level 6 License Pre-Installed 2.5-inch SATA SSD', category: 'Enterprise Drives (SSD/HDD)', supplierId: 'sup-2', supplierName: 'Vertex Systems Group', description: 'Enterprise Drives (SSD/HDD) hardware component from the Inovexa enterprise catalog.', price: 16000, cost: 10880, stock: 48, minStock: 10, unit: 'unit' },
  { id: 'prod-nvidia-mellanox-mc2210411-sr4', sku: 'INV-NVIDIA-MELLANOX-MC2210411-SR', name: 'NVIDIA Mellanox MC2210411-SR4 40Gb/s QSFP+ Optical Transceiver Module', category: 'Transceivers & Cabling', supplierId: 'sup-4', supplierName: 'NetAxis Distribution Co.', description: 'Transceivers & Cabling hardware component from the Inovexa enterprise catalog.', price: 6500, cost: 4420, stock: 64, minStock: 12, unit: 'pcs' },
  { id: 'prod-supermicro-dual-sfp-v210', sku: 'INV-SUPERMICRO-DUAL-SFP-V210', name: 'Supermicro AOC-STGN-i2S Dual-Port 10GbE SFP+ PCI-e Adapter (v2.10)', category: 'Network Adapters (NICs)', supplierId: 'sup-4', supplierName: 'NetAxis Distribution Co.', description: 'Network Adapters (NICs) hardware component from the Inovexa enterprise catalog.', price: 12000, cost: 8160, stock: 28, minStock: 8, unit: 'unit' },
  { id: 'prod-cisco-nexus-92160yc-x', sku: 'INV-CISCO-NEXUS-92160YC-X', name: 'Cisco Nexus 92160YC-X 48x 10/25Gb SFP28 + 6x 40/100Gb QSFP28 Data Center Switch', category: 'Switches & Routers', supplierId: 'sup-4', supplierName: 'NetAxis Distribution Co.', description: 'Switches & Routers hardware component from the Inovexa enterprise catalog.', price: 98000, cost: 66640, stock: 14, minStock: 4, unit: 'unit' },
  { id: 'prod-cisco-nexus-3064pq-10gx', sku: 'INV-CISCO-NEXUS-3064PQ-10GX', name: 'Cisco Nexus 3064PQ-10GX 48x 10G SFP+ + 4x 40G QSFP+ Ultra-Low Latency Switch', category: 'Switches & Routers', supplierId: 'sup-4', supplierName: 'NetAxis Distribution Co.', description: 'Switches & Routers hardware component from the Inovexa enterprise catalog.', price: 98000, cost: 66640, stock: 14, minStock: 4, unit: 'unit' },
  { id: 'prod-dell-perc-h740p-mini-mono', sku: 'INV-DELL-PERC-H740P-MINI-MONO', name: 'Dell PERC H740P Mini Mono RAID Controller Card with 8GB NV Cache', category: 'RAID & Expansion Cards', supplierId: 'sup-1', supplierName: 'Apex Semiconductors', description: 'RAID & Expansion Cards hardware component from the Inovexa enterprise catalog.', price: 22000, cost: 14960, stock: 22, minStock: 6, unit: 'unit' },
  { id: 'prod-dell-r730-poweredge', sku: 'INV-DELL-R730-POWEREDGE', name: 'Dell PowerEdge R730 Server', category: 'Servers & Systems', supplierId: 'sup-1', supplierName: 'Apex Semiconductors', description: 'Servers & Systems hardware component from the Inovexa enterprise catalog.', price: 185000, cost: 125800, stock: 8, minStock: 2, unit: 'unit' },
  { id: 'prod-dell-r740-poweredge', sku: 'INV-DELL-R740-POWEREDGE', name: 'Dell PowerEdge R740 Server', category: 'Servers & Systems', supplierId: 'sup-1', supplierName: 'Apex Semiconductors', description: 'Servers & Systems hardware component from the Inovexa enterprise catalog.', price: 185000, cost: 125800, stock: 8, minStock: 2, unit: 'unit' }
];
